### ISSUE TITLE
Proposer des issus

### ISSUE THREAD

**Issue by joellesenne** [Guetso/correction_ecrivezdujs#1]
Ton idée de correction et sympa, je me suis permis de « Forked » ton dépôt sur Github et te proposerais des issus pour tes Pulls Resquests.

Suivre le projet sur https://github.com/joellesenne/correction_ecrivezdujs

**Comment by Guetso** [comment]
Hello ! Je viens seulement de voir ton message ! Désolé ^^'
Pas de souci, en tout cas, si ça intéresse toujours hésite pas !
